# Generated by Django 5.0.7 on 2025-11-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='image',
            field=models.ImageField(upload_to='templates_app/'),
        ),
    ]
