# Generated by Django 5.2.8 on 2025-11-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0002_alter_templates_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('ai', 'AI Models'), ('UIUX', 'UI & UX'), ('mobile', 'Mobile App'), ('desktop', 'Desktop App')], max_length=20),
        ),
    ]
